# Generated by Django 5.1.2 on 2024-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
    ]
